name: StaticAnalysis

on: [push]

jobs:
  static-analisys:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Analysing the code with isort
      run: |
        isort --check sakdb todolist_example.py
    - name: Analysing the code with Mypy
      run: |
        mypy sakdb todolist_example.py --ignore-missing-imports --strict
    - name: Analysing the code with Black
      run: |
        black --check sakdb todolist_example.py
    - name: Analysing the code with Flake8
      run: |
        flake8 sakdb todolist_example.py
